# Copyright (c) 2010-2013, Regents of the University of California. 
# All rights reserved. 
#  
# Released under the BSD 3-Clause license as published at the link below.
# https://openwsn.atlassian.net/wiki/display/OW/License
'''
Creates 'docs' target to build Sphinx-based source documentation.

Requires 'sphinx-build' executable on OS search path.
'''

import os

Import('env')

# Directory is relative to parent directory, where command actually is run.
htmlDir  = os.path.join('build', 'html')

targets  = env.Command(
    htmlDir,
    'index.rst',
    'sphinx-build -b html docs {0}'.format(htmlDir)
)
Clean(targets, htmlDir)
AlwaysBuild(htmlDir)
    
if 'docs' in BUILD_TARGETS:
    print "HTML docs generated in build{0}html directory.\n".format(os.sep)

Alias('docs', targets)
